Feat/post survey result
NyangDoBaeGoPa/Meomullae-Backend pull request #3
Opened 2023-02-15 07:57 UTC by PH5555

## 🔗 References

- [Notion Task Board](link):
- [Slack](link):
- Others:

## ✔️ Required Self Checklist

- [ ] My code follows the code style of this project.
- [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## ✔️ CheckList

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation

## ⏰ Time Spent

6 hours

## 💬 Description

> Add screenshots or recordings

- answer result 저장 성공
![스크린샷 2023-02-15 오후 4 54 29](https://user-images.githubusercontent.com/47862506/218966417-bddd9bd1-36d2-4e25-a9b0-5281d0322a13.png)

- answer result 저장 실패(answer id, question id 가 틀릴경우)
![스크린샷 2023-02-15 오후 4 54 40](https://user-images.githubusercontent.com/47862506/218966601-97e97541-17ff-4bef-bc46-029a1c30f751.png)

## 🚧 Things to Note

- 결과를 저장하는 거를 트랜잭션으로 구성했습니다.
- question id, answer id가 현재 데이터베이스에 존재하지 않는 id이면 BadRequestException 처리해주었습니다.

## 🔃 Related PRs

-

2023-02-17 06:35 UTC, DonghyunKim98 requested changes
전반적으로 하드코딩에 가까워서, 객체지향적으로 아름답게 작성하면 좋겠다는 느낌은 드는데

문제는 나도 객체지향으로 프로그램을 마지막으로 작성한게 1학년 2학기 C++ 이란 말이지.. ㅠㅠㅠ

이 점에 대해서 조금 더 고민해보면 좋을것 같아! 나라도 이렇게 지금은 작성할것 같아요

2023-02-17 06:35 UTC, DonghyunKim98 commented on src/survey/survey.service.ts
> +    const queryManager = queryRunner.manager;
`const {manager : queryManager} = queryRunner`

라고 쓰는게 좀더 javascript 다운 코드입니다.

2023-02-17 06:35 UTC, DonghyunKim98 commented on src/survey/survey.service.ts
> +      if (err['code'] === '23502' && err['column'] === 'question_id')
- 상수화가 필요합니다. 무슨 에러인지 다른 사람이 읽기가 어려워요.

2023-02-17 06:35 UTC, DonghyunKim98 commented on src/survey/survey.service.ts
> +      if (err['code'] === '23502' && err['column'] === 'single_choice_answer_id')
- 상수화 필요합니다.

2023-02-17 06:37 UTC, DonghyunKim98 commented on src/survey/survey.service.ts
> +    } catch (err) {
- 이 catch 문 쪽을 여기서만 작성을 해야하는건가? DB 에러를 따로 관리할 수 있는 툴은 없는지 찾아봤으면 좋겠어.
- 너무 하드코딩에 가깝다. 이건

2023-02-18 06:29 UTC, PH5555 commented on src/survey/survey.service.ts
> +    } catch (err) {
DB 에러를 따로 관리할 수 있는 툴은 찾지 못했고, catch문을 controller나 repository 에서 작성해야한다는 견해? 는 여러개 찾았는데 사람들마다 얘기가 다르네요

2023-02-20 07:28 UTC, DonghyunKim98 requested changes

2023-02-20 07:28 UTC, DonghyunKim98 commented on src/survey/survey.service.ts
> +      }
이건 별거는 아는데, 너무 다 따박따박 붙어 있는 느낌이라서, eslint 에서

`const` - `if` 사이에는 line-break 이 필요한것 같아! 관련 설정을 해주면 좋겠어!

2023-02-23 06:56 UTC, DonghyunKim98 approved these changes

2023-02-23 06:56 UTC, merged